### ISSUE TITLE
请教几个关于opencvDNN调用graph的问题：

### ISSUE THREAD

**Issue by Ludwig-Zh** [TerryBryant/MyWork#2]
最近正在尝试用opencv3.4.1调用tensorflow模型训练的lenet，但总是运行到.forward就异常弹出，所以想请教几个问题：
1、使用graph_util.convert_variables_to_constants函数后保存为pb文件，还需要另外调用freeze_graph.py去冻结参数吗？如：
const_graph=graph_util.convert_variables_to_constants(sess, sess.graph_def,['op_output'])
with tf.gfile.FastGFile(dir+'model.pb', mode='wb') as f:
        f.write(const_graph.SerializeToString())
2、opencv3.4.1运行DNN稳定性如何，异常现象还多吗？

**Comment by TerryBryant** [comment]
1、```f.write(const_graph.SerializeToString())```得到的就是包含网络结构及参数的最终结果了，所以不需要freeze_graph.py了  
2、稳定性目前还不错，应该是内部代码完善了很多

**Comment by Ludwig-Zh** [comment]
谢谢，已经调用成功了。
